name: Build and deploy 

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node 18.x
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install Dependencies (prod)
        run: npm install

      - name: Build 🏗️
        run: |
          npm run build
        env:
          CI: true
          APP_WEATHER_API_KEY: ${{ secrets.APP_WEATHER_API_KEY}}
          APP_IP_INFO_API_KEY: ${{ secrets.APP_IP_INFO_API_KEY}}